### ISSUE TITLE
markdown에서 url링크에 괄호() 가 있는 경우 gitbook에서 올바르지 않게 표시됨

### ISSUE THREAD

**Issue by vaporize93** [skhu-sss/skhu-sss.github.io#2]
[해당링크](https://skhu-sss.github.io/skhu-forest-with-firefox.html)
4. 참고문헌의 첫번째 링크부분에 괄호가 있는 링크의 페이지 연결과 표시가 올바르지 않음.
github에서 바로 볼 때는 문제가 없으나 발행된 gitbook에서만 해당 문제를 볼 수 있음.

해당 링크 :
https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx
`https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx`

**Comment by sukso96100** [comment]
Gitbook 이 업데이터 되면서 해결된 것으로 보입니다. 이슈를 닫겠습니다.
